namespace DynaDocs.Tests.Integration;

using DynaDocs.Commands;

[Collection("Integration")]
public class FixCommandIntegrationTests : IntegrationTestBase
{
    #region Hub File Generation

    [Fact]
    public async Task Fix_GeneratesHubWithFrontmatterAndComment()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Act
        var fixCommand = FixCommand.Create();
        var fixResult = await RunAsync(fixCommand, DydoDir);

        // Assert - Hub has frontmatter at top (required for YAML parsing)
        fixResult.AssertSuccess();
        var hubContent = ReadFile("dydo/guides/_index.md");
        Assert.StartsWith("---\n", hubContent.Replace("\r\n", "\n"));

        // Assert - Hub has auto-generated comment after frontmatter
        Assert.Contains("<!-- Auto-generated by 'dydo fix'", hubContent);
    }

    [Fact]
    public async Task Fix_GeneratedHubsPassFrontmatterCheck()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Act - Run fix
        var fixCommand = FixCommand.Create();
        await RunAsync(fixCommand, DydoDir);

        // Act - Run check
        var checkResult = await CheckAsync(DydoDir);

        // Assert - No frontmatter warnings for generated hubs
        checkResult.AssertSuccess();
        Assert.DoesNotContain("guides/_index.md - Add frontmatter", checkResult.Stdout);

        // Assert - No orphan warnings (all docs are linked from generated hubs)
        Assert.DoesNotContain("Orphan doc", checkResult.Stdout);
    }

    [Fact]
    public async Task Fix_GeneratesHubWithContents()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Act
        var fixCommand = FixCommand.Create();
        var fixResult = await RunAsync(fixCommand, DydoDir);

        // Assert - Hub has contents section with links
        fixResult.AssertSuccess();
        var hubContent = ReadFile("dydo/guides/_index.md");
        Assert.Contains("## Contents", hubContent);
        Assert.Contains("coding-standards.md", hubContent);
        Assert.Contains("how-to-use-docs.md", hubContent);
    }

    [Fact]
    public async Task Fix_GeneratesHubsForAllMainFolders()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Act
        var fixCommand = FixCommand.Create();
        var fixResult = await RunAsync(fixCommand, DydoDir);

        // Assert - All main folders have generated hubs
        fixResult.AssertSuccess();

        var guidesHub = ReadFile("dydo/guides/_index.md");
        Assert.Contains("<!-- Auto-generated", guidesHub);

        var referenceHub = ReadFile("dydo/reference/_index.md");
        Assert.Contains("<!-- Auto-generated", referenceHub);

        var understandHub = ReadFile("dydo/understand/_index.md");
        Assert.Contains("<!-- Auto-generated", understandHub);

        var projectHub = ReadFile("dydo/project/_index.md");
        Assert.Contains("<!-- Auto-generated", projectHub);
    }

    [Fact]
    public async Task Fix_RegeneratesHubWhenNewFileAdded()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Run fix once
        var fixCommand = FixCommand.Create();
        await RunAsync(fixCommand, DydoDir);

        var hubContentBefore = ReadFile("dydo/guides/_index.md");
        Assert.DoesNotContain("new-guide.md", hubContentBefore);

        // Add a new file
        WriteFile("dydo/guides/new-guide.md", "---\narea: guides\ntype: guide\n---\n\n# New Guide\n\nA brand new guide.");

        // Act - Run fix again
        var secondRun = await RunAsync(fixCommand, DydoDir);

        // Assert - Hub should now include the new file
        secondRun.AssertSuccess();
        var hubContentAfter = ReadFile("dydo/guides/_index.md");
        Assert.Contains("new-guide.md", hubContentAfter);
        Assert.Contains("Updated", secondRun.Stdout);
    }

    [Fact]
    public async Task Fix_IncludesSubfolderLinks()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Create a subfolder with a doc
        WriteFile("dydo/guides/tutorials/getting-started.md",
            "---\narea: guides\ntype: guide\n---\n\n# Getting Started\n\nLearn the basics.");

        // Act - Run fix (will create subfolder hub and update parent hub)
        var fixCommand = FixCommand.Create();
        var fixResult = await RunAsync(fixCommand, DydoDir);

        // Assert - Parent hub has Subfolders section
        fixResult.AssertSuccess();
        var guidesHub = ReadFile("dydo/guides/_index.md");
        Assert.Contains("## Subfolders", guidesHub);
        Assert.Contains("tutorials/_index.md", guidesHub);

        // Subfolder hub was created
        AssertFileExists("dydo/guides/tutorials/_index.md");
        var tutorialsHub = ReadFile("dydo/guides/tutorials/_index.md");
        Assert.Contains("getting-started.md", tutorialsHub);
    }

    [Fact]
    public async Task Fix_IncludesSummariesInLinks()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Act
        var fixCommand = FixCommand.Create();
        await RunAsync(fixCommand, DydoDir);

        // Assert - Links include descriptions extracted from summary paragraphs
        var guidesHub = ReadFile("dydo/guides/_index.md");
        // coding-standards.md has a summary, should be included
        Assert.Contains(") -", guidesHub); // Format: [Title](./file.md) - Description
    }

    [Fact]
    public async Task Fix_IsIdempotent()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Act - Run fix twice
        var fixCommand = FixCommand.Create();
        var firstRun = await RunAsync(fixCommand, DydoDir);
        firstRun.AssertSuccess();

        var contentAfterFirstRun = ReadFile("dydo/guides/_index.md");

        var secondRun = await RunAsync(fixCommand, DydoDir);
        secondRun.AssertSuccess();

        var contentAfterSecondRun = ReadFile("dydo/guides/_index.md");

        // Assert - Content should be same after second run
        Assert.Equal(contentAfterFirstRun, contentAfterSecondRun);
        // Second run should not report any updates (nothing changed)
        Assert.DoesNotContain("Updated", secondRun.Stdout);
        Assert.DoesNotContain("Created", secondRun.Stdout);
    }

    [Fact]
    public async Task Fix_ReportsGeneratedHubsInOutput()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Act
        var fixCommand = FixCommand.Create();
        var fixResult = await RunAsync(fixCommand, DydoDir);

        // Assert - Output mentions generated hubs
        fixResult.AssertSuccess();
        Assert.Contains("_index.md", fixResult.Stdout);
    }

    [Fact]
    public async Task Fix_OverwritesCustomHub()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Write custom content to hub
        var hubPath = "dydo/guides/_index.md";
        WriteFile(hubPath, "# My Custom Hub\n\nThis should be overwritten.");

        // Act
        var fixCommand = FixCommand.Create();
        await RunAsync(fixCommand, DydoDir);

        // Assert - Custom content was replaced with auto-generated content
        var hubContent = ReadFile(hubPath);
        Assert.Contains("<!-- Auto-generated", hubContent);
        Assert.DoesNotContain("My Custom Hub", hubContent);
        Assert.Contains("coding-standards.md", hubContent);
    }

    [Fact]
    public async Task Fix_GeneratesCorrectFrontmatter()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Act
        var fixCommand = FixCommand.Create();
        await RunAsync(fixCommand, DydoDir);

        // Assert - Hub has correct frontmatter
        var guidesHub = ReadFile("dydo/guides/_index.md");
        Assert.Contains("area: guides", guidesHub);
        Assert.Contains("type: hub", guidesHub);

        var referenceHub = ReadFile("dydo/reference/_index.md");
        Assert.Contains("area: reference", referenceHub);
    }

    #endregion

    #region Hub File Creation

    [Fact]
    public async Task Fix_CreatesHubForNewFolder()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Create a new folder with a doc but no _index.md
        WriteFile("dydo/guides/subfolder/new-guide.md",
            "---\narea: guides\ntype: guide\n---\n\n# New Guide\n\nSome content.");

        // Act
        var fixCommand = FixCommand.Create();
        var fixResult = await RunAsync(fixCommand, DydoDir);

        // Assert - Hub file should be created
        fixResult.AssertSuccess();
        AssertFileExists("dydo/guides/subfolder/_index.md");
        var hubContent = ReadFile("dydo/guides/subfolder/_index.md");
        Assert.Contains("<!-- Auto-generated", hubContent);
        Assert.Contains("new-guide.md", hubContent);
    }

    #endregion

    #region Obsidian Compatibility

    [Fact]
    public async Task Fix_IgnoresObsidianFolder()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Create .obsidian folder with typical config files
        WriteFile("dydo/.obsidian/app.json", "{\"alwaysUpdateLinks\": true}");
        WriteFile("dydo/.obsidian/appearance.json", "{\"theme\": \"obsidian\"}");
        WriteFile("dydo/.obsidian/workspace.json", "{\"main\": {}}");

        // Act
        var fixCommand = FixCommand.Create();
        var fixResult = await RunAsync(fixCommand, DydoDir);

        // Assert - Fix should succeed without creating hub for .obsidian
        fixResult.AssertSuccess();
        Assert.DoesNotContain(".obsidian", fixResult.Stdout);
        AssertFileNotExists("dydo/.obsidian/_index.md");
    }

    [Fact]
    public async Task Check_IgnoresObsidianFolder()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Create .obsidian folder with typical config files
        WriteFile("dydo/.obsidian/app.json", "{\"alwaysUpdateLinks\": true}");
        WriteFile("dydo/.obsidian/appearance.json", "{\"theme\": \"obsidian\"}");
        WriteFile("dydo/.obsidian/workspace.json", "{\"main\": {}}");

        // Run fix to generate hubs
        var fixCommand = FixCommand.Create();
        await RunAsync(fixCommand, DydoDir);

        // Act
        var checkResult = await CheckAsync(DydoDir);

        // Assert - Check should not complain about .obsidian folder
        checkResult.AssertSuccess();
        Assert.DoesNotContain(".obsidian", checkResult.Stdout);
    }

    #endregion

    #region Meta File Generation

    [Fact]
    public async Task Fix_CreatesMetaFilesForDirectChildrenOfMainFolders()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Create a subfolder without meta file
        WriteFile("dydo/guides/getting-started/install.md",
            "---\narea: guides\ntype: guide\n---\n\n# Install\n\nHow to install.");

        // Act
        var fixCommand = FixCommand.Create();
        var fixResult = await RunAsync(fixCommand, DydoDir);

        // Assert
        fixResult.AssertSuccess();
        AssertFileExists("dydo/guides/getting-started/_getting-started.md");
        var content = ReadFile("dydo/guides/getting-started/_getting-started.md");
        Assert.Contains("type: folder-meta", content);
        Assert.Contains("# Getting Started", content);
    }

    [Fact]
    public async Task Fix_MetaFileSummaryUsedInHubLinks()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Create subfolder with meta file that has a summary
        WriteFile("dydo/guides/api/_api.md",
            "---\narea: guides\ntype: folder-meta\n---\n\n# API\n\nThis folder contains API documentation.");
        WriteFile("dydo/guides/api/endpoints.md",
            "---\narea: guides\ntype: reference\n---\n\n# Endpoints\n\nAPI endpoints.");

        // Act
        var fixCommand = FixCommand.Create();
        var fixResult = await RunAsync(fixCommand, DydoDir);

        // Assert - Hub should use meta file summary
        fixResult.AssertSuccess();
        var hubContent = ReadFile("dydo/guides/_index.md");
        Assert.Contains("This folder contains API documentation", hubContent);
    }

    [Fact]
    public async Task Fix_SkipsHiddenFoldersForMetaFiles()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Create hidden folder in guides
        WriteFile("dydo/guides/.obsidian/config.md",
            "---\narea: guides\ntype: guide\n---\n\n# Config\n\nSome config.");

        // Act
        var fixCommand = FixCommand.Create();
        var fixResult = await RunAsync(fixCommand, DydoDir);

        // Assert - Should not create meta file for hidden folder
        fixResult.AssertSuccess();
        AssertFileNotExists("dydo/guides/.obsidian/_.obsidian.md");
    }

    [Fact]
    public async Task Fix_DoesNotCreateMetaFilesForNestedFolders()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Create nested folder (project/tasks/subtask is NOT a direct child of a main folder)
        WriteFile("dydo/project/tasks/subtask/task1.md",
            "---\narea: project\ntype: guide\n---\n\n# Task 1\n\nA task.");

        // Act
        var fixCommand = FixCommand.Create();
        var fixResult = await RunAsync(fixCommand, DydoDir);

        // Assert - Should NOT create meta file for nested folder
        fixResult.AssertSuccess();
        AssertFileNotExists("dydo/project/tasks/subtask/_subtask.md");
    }

    [Fact]
    public async Task Fix_DoesNotOverwriteExistingMetaFile()
    {
        // Arrange
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Create subfolder with existing meta file
        var customContent = "---\narea: guides\ntype: folder-meta\n---\n\n# API Guides\n\nCustom description that should not be overwritten.";
        WriteFile("dydo/guides/api/_api.md", customContent);
        WriteFile("dydo/guides/api/endpoints.md",
            "---\narea: guides\ntype: reference\n---\n\n# Endpoints\n\nAPI endpoints.");

        // Act
        var fixCommand = FixCommand.Create();
        var fixResult = await RunAsync(fixCommand, DydoDir);

        // Assert - Meta file should not be overwritten
        fixResult.AssertSuccess();
        var content = ReadFile("dydo/guides/api/_api.md");
        Assert.Contains("Custom description that should not be overwritten", content);
    }

    [Fact]
    public async Task Fix_AfterInit_PreservesProjectSubfolderMetaFiles()
    {
        // Arrange - Initialize a fresh project
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Capture meta file content before fix
        var tasksMetaBefore = ReadFile("dydo/project/tasks/_tasks.md");
        var decisionsMetaBefore = ReadFile("dydo/project/decisions/_decisions.md");
        var changelogMetaBefore = ReadFile("dydo/project/changelog/_changelog.md");
        var pitfallsMetaBefore = ReadFile("dydo/project/pitfalls/_pitfalls.md");

        // Act - Run fix immediately after init
        var fixCommand = FixCommand.Create();
        var fixResult = await RunAsync(fixCommand, DydoDir);

        // Assert - Fix should succeed
        fixResult.AssertSuccess();

        // Meta files should be unchanged (not recreated by fix)
        Assert.Equal(tasksMetaBefore, ReadFile("dydo/project/tasks/_tasks.md"));
        Assert.Equal(decisionsMetaBefore, ReadFile("dydo/project/decisions/_decisions.md"));
        Assert.Equal(changelogMetaBefore, ReadFile("dydo/project/changelog/_changelog.md"));
        Assert.Equal(pitfallsMetaBefore, ReadFile("dydo/project/pitfalls/_pitfalls.md"));

        // Fix should not report creating new meta files for project subfolders
        // (they already exist from init)
        Assert.DoesNotContain("Created project/tasks/_tasks.md", fixResult.Stdout);
        Assert.DoesNotContain("Created project/decisions/_decisions.md", fixResult.Stdout);
        Assert.DoesNotContain("Created project/changelog/_changelog.md", fixResult.Stdout);
        Assert.DoesNotContain("Created project/pitfalls/_pitfalls.md", fixResult.Stdout);
    }

    [Fact]
    public async Task Fix_AfterInit_ProducesNoChanges()
    {
        // Arrange - Fresh init
        var initResult = await InitProjectAsync();
        initResult.AssertSuccess();

        // Act & Assert - Check should pass with no errors
        var checkResult = await CheckAsync(DydoDir);
        checkResult.AssertSuccess();
        Assert.DoesNotContain("Found errors", checkResult.Stdout);

        // Act - Run fix
        var fixCommand = FixCommand.Create();
        var fixResult = await RunAsync(fixCommand, DydoDir);

        // Assert - Fix should succeed with no changes
        fixResult.AssertSuccess();
        Assert.Contains("Fixed 0 issues", fixResult.Stdout);
        Assert.DoesNotContain("Created", fixResult.Stdout);
        Assert.DoesNotContain("Updated", fixResult.Stdout);
    }

    #endregion
}
