namespace DynaDocs.Tests.Commands;

using DynaDocs.Commands;
using DynaDocs.Models;
using DynaDocs.Services;

public class FixHubHandlerTests : IDisposable
{
    private readonly string _basePath;

    public FixHubHandlerTests()
    {
        _basePath = Path.Combine(Path.GetTempPath(), "fix-hub-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_basePath);
    }

    public void Dispose()
    {
        if (Directory.Exists(_basePath)) Directory.Delete(_basePath, recursive: true);
    }

    [Fact]
    public void RegenerateHubs_UpdatesExistingAutoGeneratedHub()
    {
        var decisionsDir = Path.Combine(_basePath, "project", "decisions");
        Directory.CreateDirectory(decisionsDir);
        var indexPath = Path.Combine(decisionsDir, "_index.md");
        File.WriteAllText(indexPath,
            "---\narea: project\ntype: hub\n---\n\n" + HubGenerator.AutoGenComment + "\n\n# Stale\n");

        File.WriteAllText(Path.Combine(decisionsDir, "example.md"),
            "---\narea: project\ntype: decision\n---\n\n# Example\n\nA decision.\n");

        var scanner = new DocScanner(new MarkdownParser());
        var docs = scanner.ScanDirectory(_basePath);

        FixHubHandler.RegenerateHubs(_basePath, scanner, docs);

        var content = File.ReadAllText(indexPath);
        Assert.Contains(HubGenerator.AutoGenComment, content);
        Assert.Contains("[Example](./example.md)", content);
        Assert.DoesNotContain("# Stale", content);
    }

    [Fact]
    public void RegenerateHubs_ReplacesHandWrittenHubWithGeneratedContent()
    {
        var guidesDir = Path.Combine(_basePath, "guides", "api");
        Directory.CreateDirectory(guidesDir);
        var indexPath = Path.Combine(guidesDir, "_index.md");
        var handWritten = "---\narea: project\ntype: hub\n---\n\n# Custom hand-written index\n";
        File.WriteAllText(indexPath, handWritten);

        File.WriteAllText(Path.Combine(guidesDir, "endpoints.md"),
            "---\narea: guides\ntype: guide\n---\n\n# Endpoints\n\nAPI endpoints.\n");

        var scanner = new DocScanner(new MarkdownParser());
        var docs = scanner.ScanDirectory(_basePath);

        FixHubHandler.RegenerateHubs(_basePath, scanner, docs);

        var content = File.ReadAllText(indexPath);
        Assert.NotEqual(handWritten, content);
        Assert.Contains(HubGenerator.AutoGenComment, content);
        Assert.Contains("[Endpoints](./endpoints.md)", content);
    }

    [Fact]
    public void RegenerateHubs_DoesNotRewriteHubWithPlatformLineEndings()
    {
        var guidesDir = Path.Combine(_basePath, "guides");
        Directory.CreateDirectory(guidesDir);
        File.WriteAllText(Path.Combine(guidesDir, "example.md"), """
            ---
            area: guides
            type: guide
            ---

            # Example

            Example guide summary.
            """);

        var scanner = new DocScanner(new MarkdownParser());
        var docs = scanner.ScanDirectory(_basePath);
        var guide = docs.Single(d => d.RelativePath == "guides/example.md");
        var seed = HubGenerator.GenerateHub("guides", [guide], [], docs);
        var indexPath = Path.Combine(guidesDir, "_index.md");
        File.WriteAllText(indexPath, seed.ReplaceLineEndings(Environment.NewLine));

        docs = scanner.ScanDirectory(_basePath);
        var before = File.ReadAllBytes(indexPath);
        var regenerated = -1;
        var output = ConsoleCapture.Stdout(() =>
        {
            regenerated = FixHubHandler.RegenerateHubs(_basePath, scanner, docs);
        });

        Assert.Equal(0, regenerated);
        Assert.DoesNotContain("Updated", output);
        Assert.Equal(before, File.ReadAllBytes(indexPath));
    }
}
