namespace DynaDocs.Utils;

using DynaDocs.Models;

/// <summary>
/// Path and content predicates shared by content-shape rules (Frontmatter, Title,
/// BrokenLinks, Naming) so each rule consults the same definition of "framework
/// scaffolding that shouldn't be validated as a normal doc". PR2 will move
/// the existing inline checks in those rules onto this helper.
/// </summary>
public static class RuleSkipPaths
{
    private const string LegacyHubGeneratedMarker = "<!-- Auto-generated by 'dydo fix'. Do not edit - changes will be overwritten. -->";

    public static bool IsAutoGenerated(DocFile doc)
    {
        return doc.Content.Split('\n')
            .Any(line => string.Equals(line.Trim(), LegacyHubGeneratedMarker, StringComparison.Ordinal));
    }
}
